  
name: Build ESP-AT Project

on: push

jobs:
  setup-secrets:
    uses: ./.github/workflows/setup_secrets.yml
    secrets: inherit

  build-esp32-wroom-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wroom == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROOM-32
      artifacts_name: esp32-wroom-at
    secrets: inherit

  build-esp32-wrover-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wrover == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-wrover-at
    secrets: inherit

  build-esp32-pico-d4-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_pico_d4 == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: PICO-D4
      artifacts_name: esp32-pico-d4-at
    secrets: inherit

  build-esp32-solo-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_solo_1 == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: SOLO-1
      artifacts_name: esp32-solo-1-at
    secrets: inherit

  build-esp32-d2wd-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wroom == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: ESP32-D2WD
      artifacts_name: esp32-d2wd-at
    secrets: inherit

  build-esp32-mini-1-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_mini_1 == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32-mini-1-at
    secrets: inherit

  build-esp32-sdio-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wroom == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: ESP32-SDIO
      artifacts_name: esp32-sdio-at
    secrets: inherit

  build-esp32-at-all-function-test-without-bt:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wroom == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-at-all-function-test-without-bt
    secrets: inherit

  build-esp32-at-all-function-test-just-bt:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32_wroom == 'true'
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-at-all-function-test-just-bt
    secrets: inherit

  build-esp32c3-mini-1-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c3_mini == 'true'
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32c3-mini-1-at
    secrets: inherit

  build-esp32c3-spi-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c3_mini == 'true'
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: ESP32C3-SPI
      artifacts_name: esp32c3-spi-at
    secrets: inherit

  build-esp32c3-at-full-function-test:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c3_mini == 'true'
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32c3-at-full-function-test
    secrets: inherit

  build-esp32c3-rainmaker:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c3_mini == 'true'
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: ESP32C3_RAINMAKER
      artifacts_name: esp32c3-rainmaker-at
    secrets: inherit

  build-esp32c2-4mb-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c2_4mb == 'true'
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-4MB
      artifacts_name: esp32c2-4MB-at
    secrets: inherit

  build-esp32c2-2mb-at:
    needs: [setup-secrets]
    if: needs.setup-secrets.outputs.ota_token_esp32c2_2mb == 'true'
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB
      artifacts_name: esp32c2-2MB-at
    secrets: inherit
