name: Reusable workflow template for setting up the secrets

on:
  workflow_call:
    # the secrets from upstream inherit
    secrets:
      AT_OTA_TOKEN_WROOM32:
        required: false
      AT_OTA_TOKEN_WROVER32:
        required: false
      AT_OTA_TOKEN_ESP32_MINI_1:
        required: false
      AT_OTA_TOKEN_ESP32_PICO_D4:
        required: false
      AT_OTA_TOKEN_ESP32_SOLO_1:
        required: false
      AT_OTA_TOKEN_ESP32C3_MINI:
        required: false
      ESP32C2_2MB_TOKEN:
        required: false
      ESP32C2_4MB_TOKEN:
        required: false
    # the outputs for the caller
    outputs:
      ota_token_esp32_wroom:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32_wroom }}
      ota_token_esp32_wrover:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32_wrover }}
      ota_token_esp32_mini_1:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32_mini_1 }}
      ota_token_esp32_pico_d4:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32_pico_d4 }}
      ota_token_esp32_solo_1:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32_solo_1 }}
      ota_token_esp32c3_mini:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32c3_mini }}
      ota_token_esp32c2_2mb:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32c2_2mb }}
      ota_token_esp32c2_4mb:
        value: ${{ jobs.setup-secrets.outputs.ota_token_esp32c2_4mb }}

jobs:
  setup-secrets:
    name: Check if the ota token was set on secrets
    runs-on: ubuntu-latest
    outputs:
      ota_token_esp32_wroom: ${{ steps.setvar.outputs.ota_token_esp32_wroom }}
      ota_token_esp32_wrover: ${{ steps.setvar.outputs.ota_token_esp32_wrover }}
      ota_token_esp32_mini_1: ${{ steps.setvar.outputs.ota_token_esp32_mini_1 }}
      ota_token_esp32_pico_d4: ${{ steps.setvar.outputs.ota_token_esp32_pico_d4 }}
      ota_token_esp32_solo_1: ${{ steps.setvar.outputs.ota_token_esp32_solo_1 }}
      ota_token_esp32c3_mini: ${{ steps.setvar.outputs.ota_token_esp32c3_mini }}
      ota_token_esp32c2_2mb: ${{ steps.setvar.outputs.ota_token_esp32c2_2mb }}
      ota_token_esp32c2_4mb: ${{ steps.setvar.outputs.ota_token_esp32c2_4mb }}
    steps:
      - id: setvar
        run: |
          # esp32 ota tokens
          if [[ "${{ secrets.AT_OTA_TOKEN_WROOM32 }}" != "" ]];
          then
            echo "ota_token_esp32_wroom=true" >>  $GITHUB_OUTPUT
          else
            echo "ota_token_esp32_wroom=false" >>$GITHUB_OUTPUT
          fi

          if [[ "${{ secrets.AT_OTA_TOKEN_WROVER32 }}" != "" ]];
          then
            echo "ota_token_esp32_wrover=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32_wrover=false" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ secrets.AT_OTA_TOKEN_ESP32_MINI_1 }}" != "" ]];
          then
            echo "ota_token_esp32_mini_1=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32_mini_1=false" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ secrets.AT_OTA_TOKEN_ESP32_PICO_D4 }}" != "" ]];
          then
            echo "ota_token_esp32_pico_d4=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32_pico_d4=false" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ secrets.AT_OTA_TOKEN_ESP32_SOLO_1 }}" != "" ]];
          then
            echo "ota_token_esp32_solo_1=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32_solo_1=false" >> $GITHUB_OUTPUT
          fi

          # esp32-c3 ota tokens
          if [[ "${{ secrets.AT_OTA_TOKEN_ESP32C3_MINI }}" != "" ]];
          then
            echo "ota_token_esp32c3_mini=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32c3_mini=false" >> $GITHUB_OUTPUT
          fi

          # esp32-c2 ota tokens
          if [[ "${{ secrets.ESP32C2_2MB_TOKEN }}" != "" ]];
          then
            echo "ota_token_esp32c2_2mb=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32c2_2mb=false" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ secrets.ESP32C2_4MB_TOKEN }}" != "" ]];
          then
            echo "ota_token_esp32c2_4mb=true" >> $GITHUB_OUTPUT
          else
            echo "ota_token_esp32c2_4mb=false" >> $GITHUB_OUTPUT
          fi
